// // File generated by FlutterFire CLI.
// // ignore_for_file: type=lint
// import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
// import 'package:flutter/foundation.dart'
//     show defaultTargetPlatform, kIsWeb, TargetPlatform;

// /// Default [FirebaseOptions] for use with your Firebase apps.
// ///
// /// Example:
// /// ```dart
// /// import 'firebase_options.dart';
// /// // ...
// /// await Firebase.initializeApp(
// ///   options: DefaultFirebaseOptions.currentPlatform,
// /// );
// /// ```
// class DefaultFirebaseOptions {
//   static FirebaseOptions get currentPlatform {
//     if (kIsWeb) {
//       return web;
//     }
//     switch (defaultTargetPlatform) {
//       case TargetPlatform.android:
//         return android;
//       case TargetPlatform.iOS:
//         return ios;
//       case TargetPlatform.macOS:
//         return macos;
//       case TargetPlatform.windows:
//         return windows;
//       case TargetPlatform.linux:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions have not been configured for linux - '
//           'you can reconfigure this by running the FlutterFire CLI again.',
//         );
//       default:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions are not supported for this platform.',
//         );
//     }
//   }

//   static const FirebaseOptions web = FirebaseOptions(
//     apiKey: 'AIzaSyC9pvjY_9wide5q1rA75KS7KnJIKsXgWRQ',
//     appId: '1:1052842009622:web:60d0acfc829f5a827b8137',
//     messagingSenderId: '1052842009622',
//     projectId: 'itds283-project-emm',
//     authDomain: 'itds283-project-emm.firebaseapp.com',
//     storageBucket: 'itds283-project-emm.firebasestorage.app',
//     measurementId: 'G-6YQ2EYW3MT',
//   );

//   static const FirebaseOptions android = FirebaseOptions(
//     apiKey: 'AIzaSyDkjE4rUX8oGfXExDuPKz8kPSa9rqdcgWE',
//     appId: '1:1052842009622:android:feb6319fd16b4ae37b8137',
//     messagingSenderId: '1052842009622',
//     projectId: 'itds283-project-emm',
//     storageBucket: 'itds283-project-emm.firebasestorage.app',
//   );

//   static const FirebaseOptions ios = FirebaseOptions(
//     apiKey: 'AIzaSyDVHdlnS7Mq2OrdAGyZxnikIj9XDvr5hU8',
//     appId: '1:1052842009622:ios:07f67d9094b4f0527b8137',
//     messagingSenderId: '1052842009622',
//     projectId: 'itds283-project-emm',
//     storageBucket: 'itds283-project-emm.firebasestorage.app',
//     iosBundleId: 'com.example.projectPhase2',
//   );

//   static const FirebaseOptions macos = FirebaseOptions(
//     apiKey: 'AIzaSyDVHdlnS7Mq2OrdAGyZxnikIj9XDvr5hU8',
//     appId: '1:1052842009622:ios:07f67d9094b4f0527b8137',
//     messagingSenderId: '1052842009622',
//     projectId: 'itds283-project-emm',
//     storageBucket: 'itds283-project-emm.firebasestorage.app',
//     iosBundleId: 'com.example.projectPhase2',
//   );

//   static const FirebaseOptions windows = FirebaseOptions(
//     apiKey: 'AIzaSyC9pvjY_9wide5q1rA75KS7KnJIKsXgWRQ',
//     appId: '1:1052842009622:web:ede412f84659f69a7b8137',
//     messagingSenderId: '1052842009622',
//     projectId: 'itds283-project-emm',
//     authDomain: 'itds283-project-emm.firebaseapp.com',
//     storageBucket: 'itds283-project-emm.firebasestorage.app',
//     measurementId: 'G-JGF4YLVWJ3',
//   );
// }
